---
stages:
  - test
  - release

include:
  - component: $CI_SERVER_FQDN/fsrvcorp/ci-components/golang@0.1.0
    inputs:
      stage: test
  - component: $CI_SERVER_FQDN/fsrvcorp/ci-components/semver@0.1.0
packages:
  stage: release
  image: goreleaser/goreleaser@sha256:1098a0be4da1780f9616a85f4c5050447b53e3e74804d8017ec1e2bbb1fb697a
  script:
    - git reset --hard $CI_COMMIT_SHA
    - git clean -ffdx
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        goreleaser release --skip publish --clean
      else
        goreleaser release --skip publish --clean --snapshot
      fi
  artifacts:
    paths:
      - dist/*.deb
    expire_in: 1 week

deb mirror:
  stage: release
  image: alpine@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
  only:
    - tags
  dependencies:
    - packages
  needs:
    - packages
  before_script:
    - apk add --no-cache ca-certificates curl
  script:
    - |
      for file in dist/*.deb; do
        URL="$(curl --upload-file ${file} https://t.fsrv.xyz)"
        curl -X POST --fail -F token=$CI_JOB_TOKEN -F "variables[PACKAGE_URL]=${URL}" -F ref=main https://ref.ci/api/v4/projects/185/trigger/pipeline
      done
